# serverless.yml

service: trap

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: ap-southeast-2
  memorySize: 128
  #profile: dev-account
  ## Lambda function permissions
  ## S3 permissions are needed when you want to load the config from S3, or store the logs to S3
  ## You can set permission policy statements:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:Get*
        - s3:List*
      Resource: "*"
  ## OR you can overwrite the default IAM role and use an existing one:
  #role: arn:aws:iam::YourAccountNumber:role/YourIamRole

functions:
  honeylambda:
    handler: handler.honeylambda
    ## Function level environment variable
    environment:
      ## Load configuration from 'local' file or 's3' bucket
      configFile: s3
      ## Specify the S3 bucket to load the config file from
      ## Make sure your bucket is in the same region as Lambda function
      s3Bucket: yours3bucket
      s3Key: honeyLambda/config.json
    events:
      - http:
          path: /
          method: get

#secret-access-key: rC3UfB+uO54NJzbrFS1tIIToCRDjgToCMOFu+H3f
#access-key-ID: AKIAZ63XO74E2SW5FWUJ
#slack-webhook: https://hooks.slack.com/services/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
